# Automatically generated build file. Do not edit.
COMPONENT_INCLUDES += $(PROJECT_PATH)/TIMER $(PROJECT_PATH)/TIMER/include $(PROJECT_PATH)/TIMER/include
COMPONENT_LDFLAGS +=  -L$(BUILD_DIR_BASE)/TIMER -lTIMER 
COMPONENT_LINKER_DEPS += 
COMPONENT_SUBMODULES += 
COMPONENT_LIBRARIES += TIMER
component-TIMER-build: 
