# Automatically generated build file. Do not edit.
COMPONENT_INCLUDES += $(PROJECT_PATH)/WIFI_CLIENT $(PROJECT_PATH)/WIFI_CLIENT/include
COMPONENT_LDFLAGS +=  -L$(BUILD_DIR_BASE)/WIFI_CLIENT -lWIFI_CLIENT 
COMPONENT_LINKER_DEPS += 
COMPONENT_SUBMODULES += 
COMPONENT_LIBRARIES += WIFI_CLIENT
component-WIFI_CLIENT-build: 
