# Automatically generated build file. Do not edit.
COMPONENT_INCLUDES += $(PROJECT_PATH)/WIFI_SERVER $(PROJECT_PATH)/WIFI_SERVER/include
COMPONENT_LDFLAGS +=  -L$(BUILD_DIR_BASE)/WIFI_SERVER -lWIFI_SERVER 
COMPONENT_LINKER_DEPS += 
COMPONENT_SUBMODULES += 
COMPONENT_LIBRARIES += WIFI_SERVER
component-WIFI_SERVER-build: 
