# Automatically generated build file. Do not edit.
COMPONENT_INCLUDES += $(PROJECT_PATH)/GPIO $(PROJECT_PATH)/GPIO/include $(PROJECT_PATH)/GPIO/include
COMPONENT_LDFLAGS +=  -L$(BUILD_DIR_BASE)/GPIO -lGPIO 
COMPONENT_LINKER_DEPS += 
COMPONENT_SUBMODULES += 
COMPONENT_LIBRARIES += GPIO
component-GPIO-build: 
